---
- hosts: tester
  user: root
  tasks:
    - name: install minimum modules
      yum: name={{ item }} state=installed
      with_items:
       - patch
       - gcc
       - vim
       - git
       - make
       - openssl-devel
       - tar
       - sudo
       - bzip2
    - name: create syboric link to /dev/fd
      shell: if [ ! -d /dev/fd ]; then ln -s /proc/self/fd /dev/fd; fi;
    - name: install epel
      yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
    - name: install remi
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present
    - name: install mysql
      yum: name={{ item }} state=installed enablerepo=remi
      with_items:
        - mysql
        - mysql-server
        - mysql-devel
    - name: put my.cnf
      template: src=my.cnf/my.cnf.j2 dest=/etc/my.cnf
    - name: set auto start mysql
      command: chkconfig mysqld on
    - name: restart mysql
      command: service mysqld restart
    - name: install nginx
      yum: name=nginx state=installed
    - name: create nginx log directory
      command: mkdir -p /var/log/rails/nginx/
    - name: put nginx.conf
      template: src=nginx.conf/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    - name: put rails.conf
      template: src=nginx.conf/rails.conf.j2 dest=/etc/nginx/conf.d/rails.conf
    - name: set auto start nginx
      command: chkconfig nginx on
    - name: restart nginx
      command: service nginx restart
    - name: install sqlite 
      yum: name={{ item }} state=installed
      with_items:
        - sqlite-devel
        - libxslt-devel
        - libxml2-devel
        - nodejs
        - npm

