---
- hosts: tester
  sudo: yes
  sudo_user: homepage
  vars:
      repos_dir : "~homepage/.anyenv"
      branch: master
  tasks:
    - name: install anyenv
      git: repo=https://github.com/riywo/anyenv dest={{ repos_dir }}
    - name: install anyenv(cont)
      script: anyenv.sh
    - name: install rbenv
      script: rbenv.sh
    - name: install rails
      script: rails.sh
